// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schedule.proto

package schedule;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedule.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.schedule.Date date = 4;</code>
   */
  boolean hasDate();
  /**
   * <code>.schedule.Date date = 4;</code>
   */
  schedule.Date getDate();
  /**
   * <code>.schedule.Date date = 4;</code>
   */
  schedule.DateOrBuilder getDateOrBuilder();

  /**
   * <code>string email = 5;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 5;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
