// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schedule.proto

package schedule;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedule.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
