// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schedule.proto

package schedule;

public final class scheduleImpl {
  private scheduleImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedule_Date_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedule_Date_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedule_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedule_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedule_SendReminder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedule_SendReminder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schedule_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schedule_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016schedule.proto\022\010schedule\"0\n\004Date\022\014\n\004ye" +
      "ar\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n\003day\030\003 \001(\005\"_\n\005" +
      "Event\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002 \001(\t\022\017\n\007messa" +
      "ge\030\003 \001(\t\022\034\n\004date\030\004 \001(\0132\016.schedule.Date\022\r" +
      "\n\005email\030\005 \001(\t\".\n\014SendReminder\022\017\n\007message" +
      "\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\"\"\n\017ResponseMessage" +
      "\022\017\n\007message\030\001 \001(\t2\212\001\n\010schedule\0229\n\tbookEv" +
      "ent\022\017.schedule.Event\032\031.schedule.Response" +
      "Message\"\000\022C\n\014sendReminder\022\026.schedule.Sen" +
      "dReminder\032\031.schedule.ResponseMessage\"\000B\032" +
      "\n\010scheduleB\014scheduleImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_schedule_Date_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schedule_Date_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedule_Date_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", });
    internal_static_schedule_Event_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_schedule_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedule_Event_descriptor,
        new java.lang.String[] { "Id", "Name", "Message", "Date", "Email", });
    internal_static_schedule_SendReminder_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_schedule_SendReminder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedule_SendReminder_descriptor,
        new java.lang.String[] { "Message", "Email", });
    internal_static_schedule_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_schedule_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schedule_ResponseMessage_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
