// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schedule.proto

package schedule;

public interface SendReminderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedule.SendReminder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
