// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package user;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
