// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package user;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
