// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package user;

public interface LogOutMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.LogOutMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
