// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrate.proto

package integrate;

public interface IntegrationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:integrate.Integration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
