// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integrate.proto

package integrate;

public final class integrateImpl {
  private integrateImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_integrate_Integration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_integrate_Integration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_integrate_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_integrate_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017integrate.proto\022\tintegrate\"\'\n\013Integrat" +
      "ion\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002 \001(\t\"\"\n\017Respons" +
      "eMessage\022\017\n\007message\030\001 \001(\t2T\n\tintegrate\022G" +
      "\n\rdoIntegration\022\026.integrate.Integration\032" +
      "\032.integrate.ResponseMessage\"\000(\001B\034\n\tinteg" +
      "rateB\rintegrateImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_integrate_Integration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_integrate_Integration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_integrate_Integration_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_integrate_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_integrate_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_integrate_ResponseMessage_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
